name: Deploy Sum Server

on:
  push:
    branches:
      - main  # Runs pipeline when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t abhinan6u/sum-server:latest .
          docker push abhinan6u/sum-server:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker pull abhinan6u/sum-server:latest
            docker stop sum-server || true
            docker rm sum-server || true
            docker ps -q --filter "ancestor=abhinan6u/sum-server:latest" | xargs -r docker stop
            docker ps -q --filter "ancestor=abhinan6u/sum-server:latest" | xargs -r docker rm
            docker run -d -p 3000:3000 --name sum-server abhinan6u/sum-server:latest
